<!DOCTYPE places_info [
        <!ELEMENT places_info (place+)>
        <!ELEMENT place (place_id,name,city,address,latitude,longitude,opened,group_id,group_name,group_sort,description,active,inactive_reason,created_date,updated_date)>
        <!ELEMENT place_id (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT city (#PCDATA)>
        <!ELEMENT address (#PCDATA)>
        <!ELEMENT latitude (#PCDATA)>
        <!ELEMENT longitude (#PCDATA)>
        <!ELEMENT opened (#PCDATA)>
        <!ELEMENT group_id (#PCDATA)>
        <!ELEMENT group_name (#PCDATA)>
        <!ELEMENT group_sort (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT active (#PCDATA)>
        <!ELEMENT inactive_reason (#PCDATA)>
        <!ELEMENT created_date (#PCDATA)>
        <!ELEMENT updated_date (#PCDATA)>
        ]>
<places_info>
    <place>
        <place_id>234</place_id>
        <name>Tallinna Finest ärimaja</name>
        <city>Tallinn</city>
        <address>Pärnu mnt 22</address>
        <latitude>59.4316385</latitude>
        <longitude>24.7452321</longitude>
        <opened>E-P 7:30-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>0. korrusel Rimi vastas eskalaatorite all</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2019-06-10 13:05:41.762058</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>183</place_id>
        <name>Jüri Konsum</name>
        <city>Jüri</city>
        <address>Aruküla tee 29, Jüri</address>
        <latitude>59.3579653</latitude>
        <longitude>24.9121106</longitude>
        <opened>E-P 9.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel kassade vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2013-09-06 10:57:35.397323</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>240</place_id>
        <name>Kehra Grossi Toidukaubad</name>
        <city>Kehra</city>
        <address>Kose maantee 7</address>
        <latitude>59.3345525</latitude>
        <longitude>25.3331962</longitude>
        <opened>E-P 7:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Peasissepääsu kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2019-09-12 14:30:26.612089</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>217</place_id>
        <name>Keila Grossi Toidukaubad</name>
        <city>Keila</city>
        <address>Piiri 7, Keila</address>
        <latitude>59.31322995</latitude>
        <longitude>24.422027958048</longitude>
        <opened>E-P 08:00 -22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel, peaukse kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-12-13 15:37:47.850077</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>134</place_id>
        <name>Keila Selver</name>
        <city>Keila</city>
        <address>Piiri 12</address>
        <latitude>59.31322995</latitude>
        <longitude>24.422027958048</longitude>
        <opened>E-P 08.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>apteegi vastas boksis</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2009-01-22 13:05:47.376</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>242</place_id>
        <name>Kiili Maxima</name>
        <city>Kiili</city>
        <address>Vaela tee 4</address>
        <latitude>59.309999</latitude>
        <longitude>24.834304404091</longitude>
        <opened>E-P 9:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Kassade vastas boksis</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2019-09-16 15:40:16.284192</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>205</place_id>
        <name>Kuusalu Grossi Toidukaubad</name>
        <city>Kuusalu</city>
        <address>Mäe 1, Kuusalu</address>
        <latitude>59.4477243</latitude>
        <longitude>25.42295</longitude>
        <opened>E-P 8:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Kassade kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2017-11-21 17:05:57.911255</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>133</place_id>
        <name>Laagri Maksimarket</name>
        <city>Laagri</city>
        <address>Pärnu mnt 558a</address>
        <latitude>59.341346</latitude>
        <longitude>24.613152804974</longitude>
        <opened>E-P 09.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>kassade kõrval koridori lõpus</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2009-01-20 15:23:10.57929</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>203</place_id>
        <name>Laagri Selver</name>
        <city>Laagri</city>
        <address>Pärnu mnt. 554, Tallinn</address>
        <latitude>59.353402</latitude>
        <longitude>24.6285812</longitude>
        <opened>E-P 8.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Pizzapoiste vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-01-30 10:48:21.265015</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>207</place_id>
        <name>Loo Gross</name>
        <city>Tallinn</city>
        <address>Saha tee 9, Loo</address>
        <latitude>59.4358105</latitude>
        <longitude>24.9422153</longitude>
        <opened>E-P 9:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Kassade vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2017-11-08 20:59:03.103576</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>161</place_id>
        <name>Maardu Maxima</name>
        <city>Maardu</city>
        <address>Keemikute 2</address>
        <latitude>59.4735476</latitude>
        <longitude>25.0198472</longitude>
        <opened>E-P 8:00-23:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>esimesel korrusel, kassade vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2012-09-12 22:39:19.793751</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>219</place_id>
        <name>Maardu Pärli Keskus</name>
        <city>Maardu</city>
        <address>Nurga 3, Maardu</address>
        <latitude>59.4870666</latitude>
        <longitude>25.0186801</longitude>
        <opened>E-P 9:00 - 22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel, Hesburgeri vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-12-11 15:17:41.277977</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>178</place_id>
        <name>Muuga Maxima</name>
        <city>Tallinn</city>
        <address>Altmetsa 1, Muuga</address>
        <latitude>59.4653316</latitude>
        <longitude>24.9619629</longitude>
        <opened>E-P 8.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel kassade vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2013-09-06 10:58:35.868852</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>179</place_id>
        <name>Peetri Selver</name>
        <city>Harjumaa</city>
        <address>Veesaare tee 2, Rae vald</address>
        <opened>E-P 08.00-23.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Selverisse sissepääsu juures, Kika loomapoe kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2013-11-14 09:02:49.41446</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>174</place_id>
        <name>Raudalu Konsum</name>
        <city>Tallinn</city>
        <address>Viljandi mnt. 41a, Tallinn</address>
        <opened>E-P 8.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1.korrusel koridori lõpus, Peetri Pizza vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2013-07-28 11:46:00.990358</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>156</place_id>
        <name>Saku Selver</name>
        <city>Saku</city>
        <address>Üksnurme tee 2</address>
        <latitude>59.293307</latitude>
        <longitude>24.65626145307</longitude>
        <opened>E-P 08.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Lillepoe kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2012-06-05 11:13:51.291209</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>177</place_id>
        <name>Saue Maxima</name>
        <city>Saue</city>
        <address>Ladva 1a, Saue</address>
        <latitude>59.293307</latitude>
        <longitude>24.65626145307</longitude>
        <opened>E-L 8.00-22.00, P 9.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel kassade vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2013-08-30 13:46:30.312857</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>180</place_id>
        <name>Tabasalu Rimi</name>
        <city>Tabasalu</city>
        <address>Klooga mnt 10b, Tabasalu</address>
        <opened>E-P 8:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel Pitsapoiste kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2014-02-19 11:35:48.788256</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>225</place_id>
        <name>Tallinna Arsenali Keskus</name>
        <city>Tallinn</city>
        <address>Erika 14, Tallinn</address>
        <opened>E-P 08:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Esimesel korrusel, Erika tänava poolse sissepääsu juures</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-09-24 09:37:07.425214</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>228</place_id>
        <name>Tallinna Astangu Rimi</name>
        <city>Tallinn</city>
        <address>Kotermaa tn 4, Tallinn</address>
        <opened>E-P 07:30 - 22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Esimesel korrusel juuksuri kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-09-24 09:37:46.78498</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>208</place_id>
        <name>Balti Jaama Turg</name>
        <city>Tallinn</city>
        <address>Kopli 1, Tallinn</address>
        <opened>E-R 6:30-23:00 L-P 8:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>0. korrusel MyFitnessi kõrval boksis</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2017-11-08 21:02:08.766304</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>121</place_id>
        <name>Tallinna Haabersti Rimi</name>
        <city>Tallinn</city>
        <address>Haabersti 1</address>
        <opened>E-P 08.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>peasissepääsu kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2009-01-20 15:23:10.57929</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>214</place_id>
        <name>Tallinna Hiiu Rimi</name>
        <city>Tallinn</city>
        <address>Pärnu mnt. 386</address>
        <opened>E-P 8:00 - 22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel WC-de vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-06-13 14:22:08.156493</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>126</place_id>
        <name>Tallinna Järve Keskus</name>
        <city>Tallinn</city>
        <address>Pärnu mnt. 238</address>
        <opened>E-P 08.00-23.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>teisel korrusel, Humana kaupluse kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2009-01-20 15:23:10.57929</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>185</place_id>
        <name>Tallinna Kadaka Selver</name>
        <city>Tallinn</city>
        <address>Kadaka tee 56A, Tallinn</address>
        <opened>E-P 8:00 - 23:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel infoleti kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2014-02-19 11:37:43.520305</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>213</place_id>
        <name>Tallinna Kakumäe Selver</name>
        <city>Tallinn</city>
        <address>Rannamõisa tee 6e, Tallinn</address>
        <opened>E-P 8:00 - 23:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>-1. korrusel travelaatori kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-05-08 11:35:34.968695</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>160</place_id>
        <name>Tallinna Kaubamaja</name>
        <city>Tallinn</city>
        <address>Gonsiori 2</address>
        <opened>E-P 9.00 -21.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Laikmaa tänava sissepääsu juures I korrusel</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2012-10-17 21:25:10.383609</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>233</place_id>
        <name>Tallinna Kolde Selver</name>
        <city>Tallinn</city>
        <address>Sõle tn 31</address>
        <opened>E-P 8:00-23:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel Selveri kassade kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-10-30 13:52:38.440799</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>146</place_id>
        <name>Tallinna Kristiine Keskus 1.korrus</name>
        <city>Tallinn</city>
        <address>Endla 45</address>
        <opened>E-P 08.00-23.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Prisma iseteeninduskassade vastas, SEB kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2010-10-20 14:57:08.754248</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>227</place_id>
        <name>Tallinna Kristiine Keskus 2.korrus</name>
        <city>Tallinn</city>
        <address>Endla 45</address>
        <opened>E-P 08.00-21.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>2. korrusel Sportlandi kõrval, treppidest üles, liftide juures</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-10-17 13:55:30.617358</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>199</place_id>
        <name>Tallinna Kärberi Selver</name>
        <city>Tallinn</city>
        <address>K. Kärberi 20/20a, Tallinn</address>
        <opened>E-P 09:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Sun Grill söögikoha vastas</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2016-10-04 10:14:39.215066</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>120</place_id>
        <name>Tallinna Lasnamäe Centrum (RIMI)</name>
        <city>Tallinn</city>
        <address>Mustakivi tee 13</address>
        <opened>E-P 09.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korruse koridoris, enne WC-sid</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2009-09-18 17:33:15.175825</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>220</place_id>
        <name>Tallinna Lasnamäe Maksimarket</name>
        <city>Tallinn</city>
        <address>J. Smuuli tee 43</address>
        <opened>E-P 9:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel peasissepääsu juures</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-08-22 09:59:22.351628</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>103</place_id>
        <name>Tallinna Lasnamäe Prisma</name>
        <city>Tallinn</city>
        <address>Mustakivi tee 17</address>
        <opened>E-P 24h</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>vasakpoolse sissepääsu vastas, taaraautomaadi juures</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2009-01-20 15:23:10.57929</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>175</place_id>
        <name>Tallinna Läänemere Selver</name>
        <city>Tallinn</city>
        <address>Tallinn, Läänemere tee 28</address>
        <opened>E-P 09:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1.korrusel, Apotheka apteegi kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2013-08-13 10:08:09.399899</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>164</place_id>
        <name>Tallinna Magistrali Keskus</name>
        <city>Tallinn</city>
        <address>Sõpruse pst 201/203</address>
        <opened>E-L 10:00 - 21:00, P 10:00 - 19:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>0 - korrusel, sissepääsu juures</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2012-07-24 16:42:21.355122</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>206</place_id>
        <name>Tallinna Marja Gross</name>
        <city>Tallinn</city>
        <address>Mustamäe tee 41, Tallinn</address>
        <opened>E-P 8:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Tamburis</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2017-11-06 19:52:33.544538</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>102</place_id>
        <name>Tallinna Merimetsa Selver</name>
        <city>Tallinn</city>
        <address>Paldiski mnt 56</address>
        <opened>E-P 09.00-22.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Hoone parempoolses tiivas, Merimetsa Selveri fuajees</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2009-01-20 15:23:10.57929</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>195</place_id>
        <name>Tallinna Mustamäe Keskus</name>
        <city>Tallinn</city>
        <address>A. H. Tammsaare tee 104a, Tallinn</address>
        <opened>E-P kell 08:00-23:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel kauplus MARILYN kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2016-01-22 16:08:02.126233</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>138</place_id>
        <name>Tallinna Mustika Prisma</name>
        <city>Tallinn</city>
        <address>Tammsaare tee 116</address>
        <opened>E-P 24h</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>keskuse peaukse juures, infoleti kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2010-05-31 10:46:06.651</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>231</place_id>
        <name>Tallinna Männiku Rimi</name>
        <city>Tallinn</city>
        <address>Männiku tee 100</address>
        <opened>E-P 08:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Peasissepääsu kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2019-10-14 11:03:12.504407</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>230</place_id>
        <name>Tallinna Nautica Keskus</name>
        <city>Tallinn</city>
        <address>Ahtri 9, Tallinn</address>
        <opened>E-P 08:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Esimesel korrusel, Kanela kaupluse kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-09-24 09:38:10.46898</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>235</place_id>
        <name>Tallinna Nurmenuku Rimi</name>
        <city>Tallinn</city>
        <address>Ehitajate tee 107</address>
        <opened>E-P 8:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Apteegi kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2019-09-09 06:35:21.795049</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>124</place_id>
        <name>Tallinna Nõmme Keskus</name>
        <city>Tallinn</city>
        <address>Jaama 2</address>
        <opened>E-R 09.00-19.00; L 10.00-17:00; P 10.00-15.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>teisel korrusel, Humana kaupluse kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2009-01-20 15:23:10.57929</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>232</place_id>
        <name>Tallinna Peterburi tee Rimi</name>
        <city>Tallinn</city>
        <address>Peterburi tee 98</address>
        <opened>E-P 8:00-22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel Rimi kassade kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-10-30 13:52:15.526828</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>216</place_id>
        <name>Tallinna Pirita Keskus</name>
        <city>Tallinn</city>
        <address>Merivälja tee 24</address>
        <opened>E-P 08:00 -22:00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>1. korrusel Rimi sissepääsu kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>
        <created_date>2018-06-19 09:13:36.145966</created_date>
        <updated_date>2019-12-23 03:00:02.727</updated_date>
    </place>
    <place>
        <place_id>125</place_id>
        <name>Tallinna Pirita Selver</name>
        <city>Tallinn</city>
        <address>Rummu tee 4</address>
        <opened>E-P 09.00-23.00</opened>
        <group_id>1</group_id>
        <group_name>Tallinn/Harjumaa</group_name>
        <group_sort>20</group_sort>
        <description>Selveri infoleti kõrval</description>
        <active>1</active>
        <inactive_reason></inactive_reason>